-- Question 1-- 
-- Retrieve the total number of rentals made in the Sakila database.

SELECT COUNT(RENTAL_ID) AS TOTAL_RENTALS
FROM RENTAL

-- Question 2:
-- Find the average rental duration (in days) of movies rented from the Sakila database

SELECT AVG(DATEDIFF(LAST_UPDATE, RENTAL_DATE)) AS AVG_RENTAL
FROM RENTAL

-- 3. Display the first name and last name of customers in uppercase.

SELECT UPPER(CONCAT(FIRST_NAME, ' ', LAST_NAME)) AS CUSTOMER_NAME
FROM CUSTOMER 


-- Question 4:
-- Extract the month from the rental date and display it alongside the rental ID.

SELECT RENTAL_ID, MONTH(RENTAL_DATE) 
FROM RENTAL 

-- Question 5:
-- Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
 
 SELECT CUSTOMER_ID, COUNT(RENTAL_ID) AS RENTAL_COUNT
 FROM RENTAL 
 GROUP BY CUSTOMER_ID
 
 
--  Question 6:
-- Find the total revenue generated by each store.

SELECT S.STORE_ID, SUM(P.AMOUNT) AS REVENUE
FROM CUSTOMER C
JOIN PAYMENT P ON C.CUSTOMER_ID = P.CUSTOMER_ID
JOIN STORE S ON S.STORE_ID = C.STORE_ID
GROUP BY S.STORE_ID


-- -- Question 7:
-- Determine the total number of rentals for each category of movies -- 

SELECT C.NAME AS CATEGORY_NAME, COUNT(R.RENTAL_ID) AS RENTAL_NO FROM 
CATEGORY C 
JOIN FILM_CATEGORY FC ON C.CATEGORY_ID = FC.CATEGORY_ID
JOIN INVENTORY I ON I.FILM_ID = FC.FILM_ID
JOIN RENTAL R ON R.INVENTORY_ID = I.INVENTORY_ID 
GROUP BY C.NAME
ORDER BY RENTAL_NO DESC;

-- Question 8:
-- Find the average rental rate of movies in each language.

SELECT L.NAME, AVG(F.RENTAL_RATE) AS AVG_RATE
FROM FILM F
JOIN LANGUAGE L ON F.LANGUAGE_ID = L.LANGUAGE_ID
GROUP BY L.NAME;

-- JOINS 

-- Questions 9 -
-- Display the title of the movie, customer s first name, and last name who rented it.
-- Hint: Use JOIN between the film, inventory, rental, and customer tables.

SELECT F.TITLE, C.FIRST_NAME, C.LAST_NAME
FROM FILM F 
JOIN INVENTORY I ON F.FILM_ID = I.FILM_ID 
JOIN RENTAL R ON R.INVENTORY_ID = I.INVENTORY_ID 
JOIN CUSTOMER ON C.CUSTOMER_ID = R.CUSTOMER_ID 

-- Question 10:
-- Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
 

SELECT A.FIRST_NAME, A.LAST_NAME
FROM FILM_ACTOR FA 
JOIN FILM F ON FA.FILM_ID = F.FILM_ID 
JOIN ACTOR A ON A.ACTOR_ID = FA.ACTOR_ID 
WHERE F.TITLE = 'GONE WITH THE WIND';


-- Question 11:
-- Retrieve the customer names along with the total amount they've spent on rentals.
 
SELECT CONCAT(FIRST_NAME,' ', LAST_NAME) AS C_NAME, SUM(AMOUNT) AS AMOUNT
FROM CUSTOMER C 
JOIN PAYMENT P ON C.CUSTOMER_ID = P.CUSTOMER_ID
JOIN RENTAL R ON R.CUSTOMER_ID = C.CUSTOMER_ID 
GROUP BY C.CUSTOMER_ID, C_NAME  -- Grouping by customer ID ensures accuracy



-- Question 12:
-- List the titles of movies rented by each customer in a particular city (e.g., 'London').
-- Hint: JOIN customer, address, city, rental, inventory, and film tables, then use GROUP BY.

SELECT CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS C_NAME, F.TITLE, CI.CITY
FROM CUSTOMER C 
JOIN ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID 
JOIN CITY CI ON A.CITY_ID = CI.CITY_ID   
JOIN RENTAL R ON R.CUSTOMER_ID = C.CUSTOMER_ID  
JOIN INVENTORY I ON I.INVENTORY_ID = R.INVENTORY_ID 
JOIN FILM F ON F.FILM_ID = I.FILM_ID 
WHERE CI.CITY = 'London'  -- 
GROUP BY C.CUSTOMER_ID, F.TITLE, CI.CITY;  -- 

-- Question 13:
-- Display the top 5 rented movies along with the number of times they've been rented.
-- Hint: JOIN film, inventory, and rental tables, then use COUNT () and GROUP BY, and limit the results.

SELECT F.TITLE, COUNT(R.RENTAL_ID) AS RENTAL_COUNT
FROM FILM F
JOIN INVENTORY I ON F.FILM_ID = I.FILM_ID  
JOIN RENTAL R ON R.INVENTORY_ID = I.INVENTORY_ID 
GROUP BY F.TITLE
ORDER BY RENTAL_COUNT DESC
LIMIT 5;


-- Question 14:
-- Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).
-- Hint: Use JOINS with rental, inventory, and customer tables and consider COUNT() and GROUP BY.

SELECT C.CUSTOMER_ID, COUNT(CONCAT(C.FIRST_NAME, ',', C.LAST_NAME)) AS CUSTOMER_NAME
FROM RENTAL R 
JOIN INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID 
JOIN CUSTOMER C ON C.CUSTOMER_ID = R.CUSTOMER_ID
WHERE I.STORE_ID IN (1,2)
GROUP BY C.CUSTOMER_ID
HAVING COUNT(DISTINCT I.STORE_ID) = 2;





-- Windows Function:

-- 1. Rank the customers based on the total amount they've spent on rentals.

SELECT A.CUSTOMER, A.AMOUNT_SPENT, DENSE_RANK() OVER( ORDER BY A.AMOUNT_SPENT DESC) AS RANKING 
FROM
(SELECT CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS CUSTOMER,  SUM(P.AMOUNT) AS AMOUNT_SPENT 
FROM RENTAL R 
JOIN PAYMENT P ON R.RENTAL_ID = P.RENTAL_ID 
JOIN CUSTOMER C ON C.CUSTOMER_ID = P.CUSTOMER_ID 
GROUP BY C.FIRST_NAME, C.LAST_NAME
) A 


-- 2. Calculate the cumulative revenue generated by each film over time.
 
 SELECT 
    F.TITLE, 
    P.PAYMENT_DATE, 
    SUM(P.AMOUNT) OVER (PARTITION BY F.TITLE ORDER BY P.PAYMENT_DATE) AS CUMULATIVE_REVENUE
FROM PAYMENT P
JOIN RENTAL R ON P.RENTAL_ID = R.RENTAL_ID
JOIN INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
JOIN FILM F ON I.FILM_ID = F.FILM_ID
ORDER BY F.TITLE, P.PAYMENT_DATE;

-- 3. Determine the average rental duration for each film, considering films with similar lengths.

SELECT 
    F.TITLE, 
    F.LENGTH,
    F.RENTAL_DURATION, 
    AVG(F.RENTAL_DURATION) OVER (PARTITION BY F.LENGTH) AS AVG_RENTAL_DURATION
FROM FILM F;

-- 4. Identify the top 3 films in each category based on their rental counts.

SELECT TITLE, NAME AS CATEGORY_NAME, RENTAL_COUNT, RENTAL_RANK
FROM (
    SELECT 
        F.TITLE, 
        C.NAME, 
        COUNT(R.RENTAL_ID) AS RENTAL_COUNT, 
        DENSE_RANK() OVER(PARTITION BY C.NAME ORDER BY COUNT(R.RENTAL_ID) DESC) AS RENTAL_RANK
    FROM FILM F 
    JOIN FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID 
    JOIN CATEGORY C ON C.CATEGORY_ID = FC.CATEGORY_ID 
    JOIN INVENTORY I ON I.FILM_ID = F.FILM_ID
    JOIN RENTAL R ON R.INVENTORY_ID = I.INVENTORY_ID
    GROUP BY F.TITLE, C.NAME
) A
WHERE RENTAL_RANK <= 3;


-- 5. Calculate the difference in rental counts between each customer's total rentals and the average rentals
-- across all customers.
WITH CustomerRentalCount AS (
    SELECT 
        C.CUSTOMER_ID, 
        CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS CUSTOMER_NAME,
        COUNT(R.RENTAL_ID) AS TOTAL_RENTALS
    FROM rental R
    JOIN customer C ON R.customer_id = C.customer_id
    GROUP BY C.CUSTOMER_ID, CUSTOMER_NAME
)
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    TOTAL_RENTALS, 
    ROUND(TOTAL_RENTALS - AVG(TOTAL_RENTALS) OVER (), 2) AS RENTAL_DIFF
FROM CustomerRentalCount
ORDER BY RENTAL_DIFF DESC;


-- 6. Find the monthly revenue trend for the entire rental store over time.
SELECT 
    YEAR(P.PAYMENT_DATE) AS YEARLY, 
    MONTH(P.PAYMENT_DATE) AS MONTHLY, 
    SUM(P.AMOUNT) AS TOTAL_REVENUE
FROM payment P
JOIN customer C ON P.customer_id = C.customer_id
JOIN store S ON C.store_id = S.store_id
GROUP BY YEARLY, MONTHLY
ORDER BY YEARLY, MONTHLY;


-- 7. Identify the customers whose total spending on rentals falls within the top 20% of all customers.

WITH CustomerSpending AS (
    SELECT 
        C.CUSTOMER_ID, 
        CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS NAME, 
        SUM(P.AMOUNT) AS TOTAL_SPEND
    FROM payment P
    JOIN customer C ON P.customer_id = C.customer_id
    GROUP BY C.CUSTOMER_ID, NAME
), RankedCustomers AS (
    SELECT *, 
           PERCENT_RANK() OVER (ORDER BY TOTAL_SPEND DESC) AS RANK_PERCENTILE
    FROM CustomerSpending
)
SELECT CUSTOMER_ID, NAME, TOTAL_SPEND
FROM RankedCustomers
WHERE RANK_PERCENTILE <= 0.2  -- Top 20% customers
ORDER BY TOTAL_SPEND DESC;





-- 8. Calculate the running total of rentals per category, ordered by rental count.

WITH CategoryRentalCount AS (
    SELECT 
        C.NAME AS CATEGORY, 
        COUNT(R.RENTAL_ID) AS RENTAL_COUNT
    FROM rental R
    JOIN inventory I ON R.inventory_id = I.inventory_id
    JOIN film_category FC ON I.film_id = FC.film_id
    JOIN category C ON FC.category_id = C.category_id
    GROUP BY C.NAME
)
SELECT 
    CATEGORY, 
    RENTAL_COUNT, 
    SUM(RENTAL_COUNT) OVER (ORDER BY RENTAL_COUNT DESC) AS RUNNING_TOTAL
FROM CategoryRentalCount
ORDER BY RENTAL_COUNT DESC;





-- 9. Find the films that have been rented less than the average rental 
-- count for their respective categories.
WITH FilmRentalCount AS (
    SELECT 
        F.FILM_ID, 
        F.TITLE, 
        C.CATEGORY_ID, 
        C.NAME AS CATEGORY, 
        COUNT(R.RENTAL_ID) AS RENTAL_COUNT
    FROM rental R
    JOIN inventory I ON R.inventory_id = I.inventory_id
    JOIN film F ON I.film_id = F.film_id
    JOIN film_category FC ON F.film_id = FC.film_id
    JOIN category C ON FC.category_id = C.category_id
    GROUP BY F.FILM_ID, F.TITLE, C.CATEGORY_ID, C.NAME
),
CategoryAverageRental AS (
    SELECT 
        CATEGORY_ID, 
        AVG(RENTAL_COUNT) AS AVG_RENTAL_COUNT
    FROM FilmRentalCount
    GROUP BY CATEGORY_ID
)
SELECT 
    FRC.FILM_ID, 
    FRC.TITLE, 
    FRC.CATEGORY, 
    FRC.RENTAL_COUNT, 
    CAR.AVG_RENTAL_COUNT
FROM FilmRentalCount FRC
JOIN CategoryAverageRental CAR ON FRC.CATEGORY_ID = CAR.CATEGORY_ID
WHERE FRC.RENTAL_COUNT < CAR.AVG_RENTAL_COUNT
ORDER BY FRC.CATEGORY, FRC.RENTAL_COUNT;



-- 10. Identify the top 5 months with the highest revenue and display the revenue generated in each month.
SELECT 
    DATE_FORMAT(payment_date, '%Y-%m') AS month_year,  -- Extract month and year
    SUM(amount) AS total_revenue
FROM payment
GROUP BY month_year
ORDER BY total_revenue DESC
LIMIT 5;




-- CTE -- 
-- 5 CTE Basics:
--  a. Write a query using a CTE to retrieve the distinct list of actor names and the number of films they 
--  have acted in from the actor and film_actor tables.

WITH FILMS_NO_BY_ACTORS AS (
    SELECT  
        CONCAT(A.FIRST_NAME, ' ', A.LAST_NAME) AS FULL_NAME, 
        COUNT(DISTINCT FA.FILM_ID) AS FILM_COUNT
    FROM actor A
    JOIN film_actor FA ON A.actor_id = FA.actor_id
    GROUP BY FULL_NAME
)
SELECT * FROM FILMS_NO_BY_ACTORS;

-- 6. CTE with Joins:
--  a. Create a CTE that combines information from the film and language tables to display the film title, 
--  language name, and rental rate.

WITH FILM_DETAILS AS ( 
SELECT F.TITLE, L.NAME AS LANGUAGE, F.RENTAL_RATE
FROM film F  
JOIN language L ON F.language_id = L.language_id  
) 

SELECT * FROM FILM_DETAILS

-- c\ CTE for Aggregation:
--  a. Write a query using a CTE to find the total revenue generated by each customer (sum of payments) 
--  from the customer and payment tables.

WITH PAYMENTS_BY_CUSTOMER AS ( 
SELECT CONCAT(FIRST_NAME, ' ' , LAST_NAME) AS NAME, SUM(P.AMOUNT) AS PAYMENTS
FROM CUSTOMER C 
JOIN PAYMENT P ON C.CUSTOMER_ID = P.CUSTOMER_ID
GROUP BY NAME ) 

SELECT * FROM PAYMENTS_BY_CUSTOMER;

-- D CTE with Window Functions:
--  a. Utilize a CTE with a window function to rank films based on their rental duration 
-- from the film table.
WITH FILM_RANK AS (
SELECT TITLE, RENTAL_DURATION, 
dense_rank() OVER (ORDER BY RENTAL_DURATION DESC)
FROM FILM ) 

SELECT * FROM FILM_RANK 
LIMIT 3;

-- È\ CTE and Filtering:
--  a. Create a CTE to list customers who have made more than two rentals, and then join this CTE with the 
--  customer table to retrieve additional customer details.
WITH CUSTOMER_RENTAL AS ( 
SELECT CUSTOMER_ID, COUNT(RENTAL_ID) AS RENTAL_COUNT
FROM RENTAL 
GROUP BY CUSTOMER_ID 
HAVING RENTAL_COUNT > 2 ) 

SELECT * 
FROM CUSTOMER_RENTAL CR 
JOIN CUSTOMER C ON CR.CUSTOMER_ID = C.CUSTOMER_ID

-- EC' CTE for Date Calculations:
--  a. Write a query using a CTE to find the total number of rentals made each month, considering the 
--  rental_date from the rental table

WITH MONTHLY_RENTALS AS (
    SELECT 
        DATE_PART('year', rental_date) AS rental_year,
        DATE_PART('month', rental_date) AS rental_month,
        COUNT(rental_id) AS total_rentals
    FROM rental
    GROUP BY rental_year, rental_month
    ORDER BY rental_year, rental_month
)
SELECT * FROM MONTHLY_RENTALS;


-- EE' CTE and Self-Join:

--  a. Create a CTE to generate a report showing pairs of actors who have appeared in the same film 
--  together, using the film_actor table.

WITH ACTOR_PAIRS AS (
    SELECT 
        fa1.actor_id AS actor_1,
        fa2.actor_id AS actor_2,
        fa1.film_id
    FROM film_actor fa1
    JOIN film_actor fa2 
        ON fa1.film_id = fa2.film_id 
        AND fa1.actor_id < fa2.actor_id -- Avoid duplicate pairs and self-pairing
)
SELECT 
    a1.first_name || ' ' || a1.last_name AS actor_1,
    a2.first_name || ' ' || a2.last_name AS actor_2,
    f.title AS film_title
FROM ACTOR_PAIRS ap
JOIN actor a1 ON ap.actor_1 = a1.actor_id
JOIN actor a2 ON ap.actor_2 = a2.actor_id
JOIN film f ON ap.film_id = f.film_id;


-- 12. CTE for Recursive Search:

--  a. Implement a recursive CTE to find all employees in the staff table who report to a specific manager, 
--  considering the reports_to column


WITH RECURSIVE EMP_HIERARCHY AS (
    -- Base Case: Select the manager
    SELECT staff_id, first_name, last_name, reports_to, 1 AS level
    FROM staff
    WHERE staff_id = <MANAGER_ID>  -- Replace with actual manager ID

    UNION ALL

    -- Recursive Case: Find employees reporting to the previous level
    SELECT s.staff_id, s.first_name, s.last_name, s.reports_to, eh.level + 1
    FROM staff s
    JOIN EMP_HIERARCHY eh ON s.reports_to = eh.staff_id
)
SELECT * FROM EMP_HIERARCHY;
